---
title: "SVM for R01 Project"
output: html_document
date: Apr 16, 2022
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 200)
```

```{r library,message=FALSE,warning=F}
library(dplyr)
library(magrittr)
library(lme4)
library(tidyverse)
source(knitr::purl("Metric Functions.Rmd"))
```

## Data preparation

```{r}
load('DHEC_tests_final_cohort.rda')
load("ID.split.rda")
```

```{r read data}
read.data <- function (data = DHEC_tests_final_cohort, iter = 1) {
  # Use the 1st split
  DHEC_tests_final_tr <- DHEC_tests_final_cohort %>% filter(RFA_ID %in% ID.split[[iter]]$ids.tr)
  DHEC_tests_final_te <- DHEC_tests_final_cohort %>% filter(RFA_ID %in% ID.split[[iter]]$ids.te)
  
  d_tr <- DHEC_tests_final_tr %>% 
  select(RFA_ID,TIME_DXDATE_TESTDATE,time_window_index,
         age,sex,race,risk,region,
         CD4_baseline,VL_baseline,AIDS,Months_to_ini_VS,
         VL_interpretation,VL,VS,VR,VB,VR_N,VR_size,prop_time,
         linkage,retention,visits,
         # ami,chf,pvd,cevd,dementia,copd,rheumd,pud,mld,diab,diabwc,hp,rend,canc,msld,metacanc,aids,
         ami.cum,chf.cum,pvd.cum,cevd.cum,dementia.cum,copd.cum,rheumd.cum,pud.cum,mld.cum,diab.cum,diabwc.cum,hp.cum,rend.cum,canc.cum,msld.cum,metacanc.cum,aids.cum,
         Depression,Anxiety,Psychiatric_disorder,Alcohol_use,Tobacco_use,Illicit_drug_use,
         New_Diagnoses_Rate,PrEP_to_Need_Ratio,pcp_rate,RPL_THEME1,RPL_THEME2,RPL_THEME3,RPL_THEME4,RPL_THEMES) %>% 
  na.omit()

d_te <- DHEC_tests_final_te %>% 
  select(RFA_ID,TIME_DXDATE_TESTDATE,time_window_index,
         age,sex,race,risk,region,
         CD4_baseline,VL_baseline,AIDS,Months_to_ini_VS,
         VL_interpretation,VL,VS,VR,VB,VR_N,VR_size,prop_time,
         linkage,retention,visits,
         # ami,chf,pvd,cevd,dementia,copd,rheumd,pud,mld,diab,diabwc,hp,rend,canc,msld,metacanc,aids,
         ami.cum,chf.cum,pvd.cum,cevd.cum,dementia.cum,copd.cum,rheumd.cum,pud.cum,mld.cum,diab.cum,diabwc.cum,hp.cum,rend.cum,canc.cum,msld.cum,metacanc.cum,aids.cum,
         Depression,Anxiety,Psychiatric_disorder,Alcohol_use,Tobacco_use,Illicit_drug_use,
         New_Diagnoses_Rate,PrEP_to_Need_Ratio,pcp_rate,RPL_THEME1,RPL_THEME2,RPL_THEME3,RPL_THEME4,RPL_THEMES) %>% 
  na.omit()
  return(list(d_tr, d_te))
}
```

```{r f.data.lag}
# function of generating lag variables
f.data.lag <- function(data,time_length,var_wider){
  VL <- data
  data.analysis <- VL %>% 
    group_by(RFA_ID) %>% 
    select(RFA_ID,time_window_index) %>% 
    summarise(td = max(time_window_index))
  data.analysis <- data.frame(RFA_ID = rep(data.analysis$RFA_ID,data.analysis$td)) %>% 
    group_by(RFA_ID) %>% mutate(time_window_index = 1:length(RFA_ID)) %>% 
    left_join(VL,by = c('RFA_ID','time_window_index'))

  for (name in var_wider) {
    for (k in 1:(time_length-1)) {
      name.k <- paste0(name,'_',k)
      data.analysis <- data.analysis %>% group_by(RFA_ID) %>% 
        mutate(!!name.k := lag(get(name),n = k))
    }
    # print(name)
  }
  # original data must not have missing value
  data.analysis <- data.analysis %>% na.omit() %>% as.data.frame()
  return(data.analysis)
}
```

## Lag 1 data

```{r}
var_wider <- c('VL','VS','VR','VB','VR_N','VR_size','prop_time',
               'linkage','retention','visits',
               # 'ami','chf','pvd','cevd','dementia','copd','rheumd','pud','mld','diab','diabwc','hp','rend','canc','msld','metacanc','aids',
               'ami.cum','chf.cum','pvd.cum','cevd.cum','dementia.cum','copd.cum','rheumd.cum','pud.cum','mld.cum','diab.cum','diabwc.cum','hp.cum','rend.cum','canc.cum','msld.cum','metacanc.cum','aids.cum',
               'Depression','Anxiety',"Psychiatric_disorder","Alcohol_use","Tobacco_use","Illicit_drug_use")
```

```{r}
# do not need to be selected
unselect <- c('RFA_ID', 'time_window_index', 'TIME_DXDATE_TESTDATE', 'AIDS', 'VL_interpretation', 'VL',  'VR', 'VB',  'VR_N', 'VR_size',  'prop_time', 'linkage', 'retention', 'visits',
              
              'ami.cum','chf.cum','pvd.cum','cevd.cum','dementia.cum','copd.cum','rheumd.cum','pud.cum','mld.cum','diab.cum','diabwc.cum','hp.cum','rend.cum','canc.cum','msld.cum','metacanc.cum','aids.cum',
              
               'Depression', 'Anxiety', 'Psychiatric_disorder', 'Alcohol_use', 'Tobacco_use', 'Illicit_drug_use')
```

### Tuned SVM

```{r, warning = FALSE}
library(e1071)
```

#### Radial kernel

```{r}
# using multi cores
library(doParallel)
library(foreach)
cl<- makeCluster(detectCores()-2)
registerDoParallel(cl)
```

```{r}
tst.acc.list <- list()
res.matrix.list <- list()
d_te.list <- list()
SVM_rad.best.list <- list()
y.prob.list <- list()
y.true.list <- list()

cost <- c(0.01, 0.1, 1, 10)
gamma <- c(0.01, 0.1, 1, 10)

for (iter in 1:30) {
  read_data <- read.data(data = DHEC_tests_final_cohort, iter = iter)
  d_tr <- read_data[[1]]
  d_te <- read_data[[2]]
  
  d_te.list[[iter]] <- d_te
  
  d_lag_tr <- f.data.lag(d_tr, time_length = 2, var_wider = var_wider)
  d_lag_te <- f.data.lag(d_te, time_length = 2, var_wider = var_wider)
  
  d_lag_tr <- d_lag_tr %>% dplyr::select(-unselect) %>%
    mutate(region = as.factor(region),
           VR_size_1 = as.factor(VR_size_1))
  d_lag_te <- d_lag_te %>% dplyr::select(-unselect) %>%
    mutate(region = as.factor(region),
           VR_size_1 = as.factor(VR_size_1))
  
  train.SVM <- d_lag_tr %>% mutate(VS = as.factor(VS))
  test.SVM <- d_lag_te %>% mutate(VS = as.factor(VS))
  
  res_temp <-
  foreach(i = 1:length(cost),
          .combine = rbind,
          .packages = 'e1071') %:%
  foreach(j = 1:length(gamma), .combine = c) %dopar% {
    fit <- svm(VS ~ ., data = train.SVM[sample(nrow(train.SVM), nrow(train.SVM) * 0.3),], kernel = "radial",
               cost = cost[i], gamma = gamma[j], cachesize = 1000)
    y_val <- predict(fit, newdata = test.SVM)
    mean(y_val == test.SVM$VS)
  }
  
  tst.acc.list[[iter]] <- res_temp

  m_n <- which(res_temp == max(res_temp, na.rm = TRUE), arr.ind = T)
  M <- m_n[1]
  N <- m_n[2]
  
  SVM.best <- svm(VS ~ ., data = train.SVM[sample(nrow(train.SVM), nrow(train.SVM) * 0.3),],
                  kernel = "radial", cost = cost[M], gamma = gamma[N], probability = TRUE)
  
  SVM_rad.best.list[[iter]] <- SVM.best
  
  y.prob <- predict(SVM.best, newdata = test.SVM, probability = TRUE)
  y.prob <- attr(y.prob, 'probabilities')
  y.hat <- predict(SVM.best, newdata = test.SVM)
  y <- test.SVM$VS
  
  y.prob.list[[iter]] <- y.prob
  y.true.list[[iter]] <- y
  
  accuracy <- Accuracy(y,y.hat)
  auc <- AUC(as.numeric(y),as.numeric(y.hat))
  recall <- Recall(y,y.hat)
  precision <- Precision(y,y.hat)
  f1 <- F1(y,y.hat)
  youden <- Youden(y,y.hat)
  
  col_names <- c('Accuracy','AUC','Recall','Precision','F1 Score','Youden Index')
  res.matrix <- matrix(c(accuracy,auc,recall,precision,f1,youden), nrow = 1)
  colnames(res.matrix) <- col_names
  
  res.matrix.list[[iter]] <- res.matrix
}
```

```{r}
save(tst.acc.list, res.matrix.list, 
     d_te.list, SVM_rad.best.list, y.prob.list, y.true.list,
     file = 'SVM_rad_30_Lag1.rda')
```

```{r}
stopCluster(cl)
```

## Lag 3 data

### Tuned SVM

#### Radial kernel

```{r}
cl<- makeCluster(detectCores()-2)
registerDoParallel(cl)
```

```{r}
tst.acc.list <- list()
res.matrix.list <- list()
d_te.list <- list()
SVM_rad.best.list <- list()
y.prob.list <- list()
y.true.list <- list()

cost <- c(0.01, 0.1, 1, 10)
gamma <- c(0.01, 0.1, 1, 10)

for (iter in 1:30) {
  read_data <- read.data(data = DHEC_tests_final_cohort, iter = iter)
  d_tr <- read_data[[1]]
  d_te <- read_data[[2]]
  
  d_te.list[[iter]] <- d_te
  
  d_lag_tr <- f.data.lag(d_tr, time_length = 4, var_wider = var_wider)
  d_lag_te <- f.data.lag(d_te, time_length = 4, var_wider = var_wider)
  
  d_lag_tr <- d_lag_tr %>% dplyr::select(-unselect) %>%
    mutate(region = as.factor(region),
           VR_size_1 = as.factor(VR_size_1),
           VR_size_2 = as.factor(VR_size_2),
           VR_size_3 = as.factor(VR_size_3))
  d_lag_te <- d_lag_te %>% dplyr::select(-unselect) %>%
    mutate(region = as.factor(region),
           VR_size_1 = as.factor(VR_size_1),
           VR_size_2 = as.factor(VR_size_2),
           VR_size_3 = as.factor(VR_size_3))
  
  train.SVM <- d_lag_tr %>% mutate(VS = as.factor(VS))
  test.SVM <- d_lag_te %>% mutate(VS = as.factor(VS))
  
  res_temp <-
  foreach(i = 1:length(cost),
          .combine = rbind,
          .packages = 'e1071') %:%
  foreach(j = 1:length(gamma), .combine = c) %dopar% {
    fit <- svm(VS ~ ., data = train.SVM[sample(nrow(train.SVM), nrow(train.SVM) * 0.3),], kernel = "radial",
               cost = cost[i], gamma = gamma[j], cachesize = 1000)
    y_val <- predict(fit, newdata = test.SVM)
    mean(y_val == test.SVM$VS)
  }
  
  tst.acc.list[[iter]] <- res_temp

  m_n <- which(res_temp == max(res_temp, na.rm = TRUE), arr.ind = T)
  M <- m_n[1]
  N <- m_n[2]
  
  SVM.best <- svm(VS ~ ., data = train.SVM[sample(nrow(train.SVM), nrow(train.SVM) * 0.3),],
                  kernel = "radial", cost = cost[M], gamma = gamma[N], probability = TRUE)
  
  SVM_rad.best.list[[iter]] <- SVM.best
  
  y.prob <- predict(SVM.best, newdata = test.SVM, probability = TRUE)
  y.prob <- attr(y.prob, 'probabilities')
  y.hat <- predict(SVM.best, newdata = test.SVM)
  y <- test.SVM$VS
  
  y.prob.list[[iter]] <- y.prob
  y.true.list[[iter]] <- y
  
  accuracy <- Accuracy(y,y.hat)
  auc <- AUC(as.numeric(y),as.numeric(y.hat))
  recall <- Recall(y,y.hat)
  precision <- Precision(y,y.hat)
  f1 <- F1(y,y.hat)
  youden <- Youden(y,y.hat)
  
  col_names <- c('Accuracy','AUC','Recall','Precision','F1 Score','Youden Index')
  res.matrix <- matrix(c(accuracy,auc,recall,precision,f1,youden), nrow = 1)
  colnames(res.matrix) <- col_names
  
  res.matrix.list[[iter]] <- res.matrix
}
```

```{r}
save(tst.acc.list, res.matrix.list, 
     d_te.list, SVM_rad.best.list, y.prob.list, y.true.list,
     file = 'SVM_rad_30_Lag3.rda')
```

```{r}
stopCluster(cl)
```

## Lag 5 data

### Tuned SVM

#### Radial kernel

```{r}
cl<- makeCluster(detectCores()-2)
registerDoParallel(cl)
```

```{r}
tst.acc.list <- list()
res.matrix.list <- list()
d_te.list <- list()
SVM_rad.best.list <- list()
y.prob.list <- list()
y.true.list <- list()

cost <- c(0.01, 0.1, 1, 10)
gamma <- c(0.01, 0.1, 1, 10)

for (iter in 1:30) {
  read_data <- read.data(data = DHEC_tests_final_cohort, iter = iter)
  d_tr <- read_data[[1]]
  d_te <- read_data[[2]]
  
  d_te.list[[iter]] <- d_te
  
  d_lag_tr <- f.data.lag(d_tr, time_length = 6, var_wider = var_wider)
  d_lag_te <- f.data.lag(d_te, time_length = 6, var_wider = var_wider)
  
  d_lag_tr <- d_lag_tr %>% dplyr::select(-unselect) %>%
    mutate(region = as.factor(region),
           VR_size_1 = as.factor(VR_size_1),
           VR_size_2 = as.factor(VR_size_2),
           VR_size_3 = as.factor(VR_size_3),
           VR_size_4 = as.factor(VR_size_4),
           VR_size_5 = as.factor(VR_size_5))
  d_lag_te <- d_lag_te %>% dplyr::select(-unselect) %>%
    mutate(region = as.factor(region),
           VR_size_1 = as.factor(VR_size_1),
           VR_size_2 = as.factor(VR_size_2),
           VR_size_3 = as.factor(VR_size_3),
           VR_size_4 = as.factor(VR_size_4),
           VR_size_5 = as.factor(VR_size_5))
  
  train.SVM <- d_lag_tr %>% mutate(VS = as.factor(VS))
  test.SVM <- d_lag_te %>% mutate(VS = as.factor(VS))
  
  res_temp <-
  foreach(i = 1:length(cost),
          .combine = rbind,
          .packages = 'e1071') %:%
  foreach(j = 1:length(gamma), .combine = c) %dopar% {
    fit <- svm(VS ~ ., data = train.SVM[sample(nrow(train.SVM), nrow(train.SVM) * 0.3),], kernel = "radial",
               cost = cost[i], gamma = gamma[j], cachesize = 1000)
    y_val <- predict(fit, newdata = test.SVM)
    mean(y_val == test.SVM$VS)
  }
  
  tst.acc.list[[iter]] <- res_temp

  m_n <- which(res_temp == max(res_temp, na.rm = TRUE), arr.ind = T)
  M <- m_n[1]
  N <- m_n[2]
  
  SVM.best <- svm(VS ~ ., data = train.SVM[sample(nrow(train.SVM), nrow(train.SVM) * 0.3),],
                  kernel = "radial", cost = cost[M], gamma = gamma[N], probability = TRUE)
  
  SVM_rad.best.list[[iter]] <- SVM.best
  
  y.prob <- predict(SVM.best, newdata = test.SVM, probability = TRUE)
  y.prob <- attr(y.prob, 'probabilities')
  y.hat <- predict(SVM.best, newdata = test.SVM)
  y <- test.SVM$VS
  
  y.prob.list[[iter]] <- y.prob
  y.true.list[[iter]] <- y
  
  accuracy <- Accuracy(y,y.hat)
  auc <- AUC(as.numeric(y),as.numeric(y.hat))
  recall <- Recall(y,y.hat)
  precision <- Precision(y,y.hat)
  f1 <- F1(y,y.hat)
  youden <- Youden(y,y.hat)
  
  col_names <- c('Accuracy','AUC','Recall','Precision','F1 Score','Youden Index')
  res.matrix <- matrix(c(accuracy,auc,recall,precision,f1,youden), nrow = 1)
  colnames(res.matrix) <- col_names
  
  res.matrix.list[[iter]] <- res.matrix
}
```

```{r}
save(tst.acc.list, res.matrix.list, 
     d_te.list, SVM_rad.best.list, y.prob.list, y.true.list,
     file = 'SVM_rad_30_Lag5.rda')
```

```{r}
stopCluster(cl)
```
